engines: 
  eslint: 
    checks: 
      quotes: 
        enabled: false
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - javascript
  nodesecurity:
    enabled: true
exclude_paths: 
  - test/**/*
ratings: 
  paths: 
    - lib/**